### ISSUE TITLE
The command to run the container

### ISSUE THREAD

**Issue by hekimgil** [AaronJackson/vrn-docker#1]
I am very new to Docker so it might be my mistake but the line you provided to run the Docker container did not work for me.

The original line was:

`docker run -v $(pwd)/data:/data:Z asjackson:vrn /runner/run.sh /data/turing.jpg`

I had to:
1. change the paranthesis into curly brackets
2. change the colon symbol ":" to slash "/"

This is the command that worked for me:
`docker run -v ${pwd}/data:/data:Z asjackson/vrn /runner/run.sh /data/turing.jpg`

And thank you very much for sharing your work and the Docker container.

**Comment by AaronJackson** [comment]
Hey, thanks.

I will fix number 2. For number 1, I'm a bit confused. Are you using
bash or some other shell?  Under bash, `echo $(pwd)` will echo the
current path. Are you using zsh, fish or something?

Aaron

hekimgil writes:

> I am very new to Docker so it might be my mistake but the line you provided to run the Docker container did not work for me.
>
> The original line was:
>
> `docker run -v $(pwd)/data:/data:Z asjackson:vrn /runner/run.sh /data/turing.jpg`
>
> I had to:
> 1. change the paranthesis into curly brackets
> 2. change the colon symbol ":" to slash "/"
>
> This is the command that worked for me:
> `docker run -v ${pwd}/data:/data:Z asjackson/vrn /runner/run.sh /data/turing.jpg`
>
> And thank you very much for sharing your work and the Docker container.

**Comment by hekimgil** [comment]
Oh, I was trying it out with Windows PowerShell. If I use the "$pwd" with "echo" or "ls", it works fine even without the paranthesis or curly brackets. With the "docker" command, it does not seem to work with the paranthesis, but curly brackets work fine.

But after reading your message, I tested it with a Ubuntu command line, and there, it works the opposite way: paranthesis work fine, curly brackets don't... And the echo command works fine only with paranthesis, not with curly brackets or without any symbols.

So, I guess number 1 is a compatibility issue between Windows and Linux command lines. It might be a better idea to leave it as it is, possibly with a small note to change paranthesis to curly brackets for Windows PowerShell?
