### ISSUE TITLE
Unable to run file

### ISSUE THREAD

**Issue by ElMutanto** [AaronJackson/vrn-docker#10]
So, I've installed the Docker and followed all of the steps mentioned and even asked a programmer friend for me, but the container keeps exiting without any prompt and no visible effect. 

From what I gather, the docker cannot find a folder with the file which is on my c: drive.

this is the thing I'm getting as a result:

```
ls: cannot access /data: No such file or directory
Please wait. Your image is being processed.
convert: no images defined `/tmp//' @ error/convert.c/ConvertImageCommand/3235.
Initialising python libs...
Initialising detector...
/root/usr/local/torch/install/bin/luajit: /root/usr/local/torch/install/share/lua/5.1/dok/inline.lua:738: <image.load> unable to determine image type for file: /tmp//
stack traceback:
[C]: in function 'error'
/root/usr/local/torch/install/share/lua/5.1/dok/inline.lua:738: in function 'error'
/root/usr/local/torch/install/share/lua/5.1/image/init.lua:390: in function 'load'
main.lua:33: in main chunk
[C]: in function 'dofile'
...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
[C]: at 0x00406460
rm: cannot remove '/tmp/': Is a directory
The face detector failed to find your face.
```

**Comment by AaronJackson** [comment]
Hey @ElMutanto, not sure if it will run on Windows. 
Under Linux, the `-v` flag specifies a volume. In the example I have `-v $PWD/data:/data` - this mounts the local folder data to `/data` inside the container. Take a look at the Windows specific parts of this doc. Hopefully it will help you get it working: https://docs.docker.com/storage/volumes/

**Comment by ElMutanto** [comment]
I managed to run it <3 Thank you!

**Comment by sqlartist** [comment]
> I managed to run it <3 Thank you!

can you show the command line you used to get it working on windows?

**Comment by ElMutanto** [comment]
> > I managed to run it <3 Thank you!
> 
> can you show the command line you used to get it working on windows?

docker run -v $PWD/data:/data:Z asjackson/vrn /runner/run.sh /data/turing.jpg
