### ISSUE TITLE
Cant find the file on Docker hub?

### ISSUE THREAD

**Issue by XEODIX** [AaronJackson/vrn-docker#12]
Hey, im new to the whole social codework thing, but i managed to get  CorentinJ /
Real-Time-Voice-Cloning working, somewhat, so i know a little bit of the calls and runs (i guess), i'm trying to find the link to it on docker, but i cant, i don't know what i'm doing there, real talk..

**Comment by AaronJackson** [comment]
What are you looking for?  I think you are in completely the wrong repo sorry.

**Comment by XEODIX** [comment]
hey, again, i went to dockerhub looking the 3D face maker, sorry it took me so long to reply, i couldn't find it on docker hub
