### ISSUE TITLE
Output questions?

### ISSUE THREAD

**Issue by JL-Works** [AaronJackson/vrn-docker#22]
Can't seem to find the files out of docker, not sure what directory these files goes to from docker.

**Comment by AaronJackson** [comment]
The output should appear as a .obj file in the input directory.

**Comment by JL-Works** [comment]
okay, whats the default location? i haven't set my location and ran it, it ran somewhere, i think.

**Comment by AaronJackson** [comment]
You have to specify a path to bind the input directory to. Please see the readme about how to run the container. It will create the output in the input directory if a face is found.
