### ISSUE TITLE
Failing to run the container

### ISSUE THREAD

**Issue by mben0** [AaronJackson/vrn-docker#25]
After pulling the image and running the container:

`sudo docker run -v $PWD/data:/data:Z asjackson/vrn /runner/run.sh /data/turing.jpg`

I get the following output in terminal:

> Please wait. Your image is being processed.
convert: unable to open image `/data/turing.jpg': No such file or directory @ error/blob.c/OpenBlob/2882.
convert: no images defined `/tmp//turing.jpg' @ error/convert.c/ConvertImageCommand/3235.
Initialising python libs...
Initialising detector...
/root/usr/local/torch/install/bin/luajit: /root/usr/local/torch/install/share/lua/5.1/image/init.lua:367: /tmp//turing.jpg: No such file or directory
stack traceback:
        [C]: in function 'error'
        /root/usr/local/torch/install/share/lua/5.1/image/init.lua:367: in function 'load'
        main.lua:33: in main chunk
        [C]: in function 'dofile'
        ...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: at 0x00406460
rm: cannot remove '/tmp//turing.jpg': No such file or directory
The face detector failed to find your face.

Thank you

**Comment by JaredTamana** [comment]
As you can see in the log:

`/tmp//turing.jpg: No such file or directory`

In your command

`sudo docker run -v $PWD/data:/data:Z asjackson/vrn /runner/run.sh /data/turing.jpg`

You have just straight copied what was in the readme. The readme says `turing.jpg` is included, but it is not. If you continue to read the readme: "An example image of Alan Turing is available in the folder data, this needs to be bind mounted to /data in the container"

So, `sudo cp path/to/yourimage.jpg data/`.

Then, when running the program, ensure you substitute `/data/turing.jpg` for `/data/`[the name of your file goes here]

A little bit of self-education as to what you're running in your commands will go a long way.
