### ISSUE TITLE
Foto

### ISSUE THREAD

**Issue by Noel212** [AaronJackson/vrn-docker#27]
Foto

**Comment by Noel212** [comment]
![image](https://user-images.githubusercontent.com/131613439/233857446-54d13634-2f7b-489f-8143-9b05a080dd83.jpeg)

**Comment by Noel212** [comment]
3d

**Comment by Noel212** [comment]
3d face ![image](https://user-images.githubusercontent.com/131613439/233857590-87a27705-69da-471f-837d-3b35ad36bcdf.jpeg)

**Comment by AaronJackson** [comment]
please stop spamming my email with photos of yourself and read the readme file
https://github.com/AaronJackson/vrn-docker
