### ISSUE TITLE
Large Pose 3D Face Reconstruction from a Single Image - file exe ??

### ISSUE THREAD

**Issue by ArtemideArte** [AaronJackson/vrn-docker#4]
Hello, I have used your "Large Pose 3D Face Reconstruction from a Single Image" program to great benefit.
Now I would like to download it to my PC but I have serious difficulties because I have no technical skills. There is no exe file for your program?
Thank You very much. Best regards. Silvia (Milan, Italy)

**Comment by rcamp5656** [comment]
I too am looking for an EXE file to make square dance figurines , or if ou could point me out to some then it would be appreciated, Russ Campbell, Kitchener, Ontario, Canada

**Comment by ArtemideArte** [comment]
Try this:
https://www.posersoftware.com/
https://anatomy360.info/
https://terawell.net/terawell/?page_id=20251
https://www.heroforge.com/
https://webapp.magicposer.com/     (this is an online app like "*Pose 3D
Face*" but it's only for the body !!)
https://figurosity.com/
https://www.daz3d.com/
https://www.deviantart.com/rivenart/art/Artist-Pose-Tool-3D-for-Android-iPhone-iPad-345216356
https://creazilla.com/nodes/64464-muscled-mannequin-man-3d-model
https://app.justsketch.me/      (this is an other online app)
https://thegraphicassembly.com/3d-anatomy-pose-reference-for-artists/

unfortunately none of these apps is similar to the one I need, the "*Large
Pose 3D Face Reconstruction from a Single Image*"  😭
hello and good luck!
Silvia


Il giorno mar 3 ago 2021 alle ore 00:25 rcamp5656 ***@***.***>
ha scritto:
