### ISSUE TITLE
Large Pose 3D Face Reconstruction from a Single Image

### ISSUE THREAD

**Issue by ArtemideArte** [AaronJackson/vrn-docker#5]
Hello everyone, I wanted to tell you my vicissitudes in trying to install the "Pose 3D Face Reconstruction" program on my PC that uses "Windows 10"
A sister of mine tried and this is what she wrote to me: "The program in question is a version that can only be run on a virtual container system running on Linux. At this point I raise my hands and give up. Not I can start installing Linux and then fumble about installing Docker and then move on to figuring out how to make the program work. It's way too much "
... and so I'm without the program I loved so much.
Is there really no simpler system ????
(Thanks everyone for your attention) Silvia

**Comment by AaronJackson** [comment]
I believe some people have had some success running it on Windows, but it's not a platform I (want to) use so I've not done any testing.
