### ISSUE TITLE
cannot remove '/tmp//turing.jpg'

### ISSUE THREAD

**Issue by ghost** [AaronJackson/vrn-docker#6]
I am on the latest version of Ubuntu (21).

I pulled the pre-built docker image: 

`sudo docker pull asjackson/vrn:latest
`

I ran it using:

`docker run -v $PWD/data:/data:Z asjackson/vrn /runner/run.sh /data/turing.jpg
`

Unfortunately I am getting this error:

```
Please wait. Your image is being processed.
convert: unable to open image `/data/turing.jpg': No such file or directory @ error/blob.c/OpenBlob/2882.
convert: no images defined `/tmp//turing.jpg' @ error/convert.c/ConvertImageCommand/3235.
Initialising python libs...	
Initialising detector...	
/root/usr/local/torch/install/bin/luajit: /root/usr/local/torch/install/share/lua/5.1/image/init.lua:367: /tmp//turing.jpg: No such file or directory
stack traceback:
	[C]: in function 'error'
	/root/usr/local/torch/install/share/lua/5.1/image/init.lua:367: in function 'load'
	main.lua:33: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406460
rm: cannot remove '/tmp//turing.jpg': No such file or directory
The face detector failed to find your face.
```

**Comment by AaronJackson** [comment]
It's because data/turing.jpg doesn't exist
Make the data in the working directory and copy a face image there. The last argument is the path to the image, prefixed with a forward slash (because that's how it's mounted inside the container)

**Comment by ghost** [comment]
Thanks for the response, I realized that the data directory was emtpy but I opened an issue because I thought it was supposed to be filled with that file.

**Comment by AaronJackson** [comment]
only if you clone the repo! :-)
