### ISSUE TITLE
Unable to modify image

### ISSUE THREAD

**Issue by ghost** [AaronJackson/vrn-docker#8]
I apologize for this issue as it's more of a docker question.

I wanted to try making a change to one of the scripts after pulling the image.

I did the following:

```
sudo docker pull asjackson/vrn:latest

docker run -t -i --entrypoint bash asjackson/vrn
```

I was able to start an interactive session and make the changes that I want.

Then I was able to commit the changes to a new image with:

```
docker commit hash new_image
```

After trying to run your command using new_image instead of asjackson/vrn, I am getting errors:

```
Please wait. Your image is being processed.
convert: no images defined `/tmp//' @ error/convert.c/ConvertImageCommand/3235.
Initialising python libs...	
Initialising detector...	
/root/usr/local/torch/install/bin/luajit: /root/usr/local/torch/install/share/lua/5.1/dok/inline.lua:738: <image.load> unable to determine image type for file: /tmp//
stack traceback:
	[C]: in function 'error'
	/root/usr/local/torch/install/share/lua/5.1/dok/inline.lua:738: in function 'error'
	/root/usr/local/torch/install/share/lua/5.1/image/init.lua:390: in function 'load'
	main.lua:33: in main chunk
	[C]: in function 'dofile'
	...ocal/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406460
rm: cannot remove '/tmp/': Is a directory
The face detector failed to find your face.
```

I have tried doing this even without modifying anything before committing, it always fails with this error.

Any help would be much appreciated.

**Comment by AaronJackson** [comment]
The script expects an image name - bit difficult to know what you've changed without some code

**Comment by ghost** [comment]
I am getting that error even without changing anything, just by doing:

```
docker run -t -i --entrypoint bash asjackson/vrn

docker commit hash new_image

docker run -v $PWD/data:/data:Z new_image /runner/run.sh /data/turing.jpg
```
I have also tried committing to same image + a tag rather than creating a new one, same issue.

`docker commit hash asjackson/vrn:v2
`

What would be the way to make any change to the image and run it?

It seems to me that something in the script is referencing something from the previous image that is no longer there, or something along those lines. I don't have another way to explain why it fails with an image that is identical with the previous.

**Comment by AaronJackson** [comment]
Sorry for the slow response.
Did you clone this repo so you have `/data/turing.jpg`?
